/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.XacNhanController;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.BaoCaoModel;
import model.GheModel;
import model.PhimModel;
import model.PhongChieuModel;
import model.SuatChieuModel;
import model.VeModel;

/**
 *
 * @author nnminh322
 */
public class XacNhan extends javax.swing.JFrame {

    private PhimModel phimModel;
    private SuatChieuModel suatChieuModel;
    private PhongChieuModel phongChieuModel;
    private GheModel gheModel;
    private VeModel veModel;
    private BaoCaoModel baoCaoModel;
    public HomeUI homeUI;
    private XacNhanController xacNhanController;

    /**
     * Creates new form XacNhan
     */
    public XacNhan() {
        initComponents();
        init();
    }

    public XacNhan(HomeUI homeUI, PhimModel phimModel) {
        this.phimModel = phimModel;
        this.homeUI = homeUI;
        initComponents();
        init();
    }

    public XacNhan(HomeUI homeUI, SuatChieuModel suatChieuModel) {
        this.suatChieuModel = suatChieuModel;
        this.homeUI = homeUI;
        initComponents();
        init();

    }

    public XacNhan(HomeUI homeUI, PhongChieuModel phongChieuModel) {
        this.phongChieuModel = phongChieuModel;
        this.homeUI = homeUI;
        initComponents();
        init();

    }

    public XacNhan(HomeUI homeUI, GheModel gheModel) {
        this.gheModel = gheModel;
        this.homeUI = homeUI;
        initComponents();
        init();

    }

    public XacNhan(HomeUI homeUI, VeModel veModel) {
        this.veModel = veModel;
        this.homeUI = homeUI;
        initComponents();
        init();
    }

    public XacNhan(HomeUI homeUI, BaoCaoModel baoCaoModel) {
        this.baoCaoModel = baoCaoModel;
        this.homeUI = homeUI;
        initComponents();
        init();

    }

    public void init() {
        this.xacNhanController = new XacNhanController(this);
        ActionListener action = new XacNhanController(this);
        this.jButton_DongY.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_DongY = new javax.swing.JButton();
        jButton_Huy = new javax.swing.JButton();
        jLabel_Tittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_DongY.setText("Đồng ý");
        jButton_DongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DongYActionPerformed(evt);
            }
        });

        jButton_Huy.setText("Huỷ");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });

        jLabel_Tittle.setText("Xác nhận xoá?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_DongY)
                        .addGap(54, 54, 54)
                        .addComponent(jButton_Huy))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel_Tittle)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Huy)
                    .addComponent(jButton_DongY))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jButton_DongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DongYActionPerformed
        // TODO add your handling code here:
        this.homeUI.hienthi();
    }//GEN-LAST:event_jButton_DongYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DongY;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Tittle;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_DongY() {
        return jButton_DongY;
    }

    public void setjButton_DongY(JButton jButton_DongY) {
        this.jButton_DongY = jButton_DongY;
    }

    public JButton getjButton_Huy() {
        return jButton_Huy;
    }

    public void setjButton_Huy(JButton jButton_Huy) {
        this.jButton_Huy = jButton_Huy;
    }

    public JLabel getjLabel_Tittle() {
        return jLabel_Tittle;
    }

    public void setjLabel_Tittle(JLabel jLabel_Tittle) {
        this.jLabel_Tittle = jLabel_Tittle;
    }

    public PhimModel getPhimModel() {
        return phimModel;
    }

    public void setPhimModel(PhimModel phimModel) {
        this.phimModel = phimModel;
    }

    public SuatChieuModel getSuatChieuModel() {
        return suatChieuModel;
    }

    public void setSuatChieuModel(SuatChieuModel suatChieuModel) {
        this.suatChieuModel = suatChieuModel;
    }

    public PhongChieuModel getPhongChieuModel() {
        return phongChieuModel;
    }

    public void setPhongChieuModel(PhongChieuModel phongChieuModel) {
        this.phongChieuModel = phongChieuModel;
    }

    public GheModel getGheModel() {
        return gheModel;
    }

    public void setGheModel(GheModel gheModel) {
        this.gheModel = gheModel;
    }

    public VeModel getVeModel() {
        return veModel;
    }

    public void setVeModel(VeModel veModel) {
        this.veModel = veModel;
    }

    public BaoCaoModel getBaoCaoModel() {
        return baoCaoModel;
    }

    public void setBaoCaoModel(BaoCaoModel baoCaoModel) {
        this.baoCaoModel = baoCaoModel;
    }

    public XacNhanController getXacNhanController() {
        return xacNhanController;
    }

    public void setXacNhanController(XacNhanController xacNhanController) {
        this.xacNhanController = xacNhanController;
    }

}
